on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' # Use a supported version
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter build apk --release --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Generate Date String
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
      - name: Rename APK and IPA Files
        run: |
          mv build/app/outputs/apk/release/app-x86_64-release.apk build/app/outputs/apk/release/app-x86_64-release-${{ env.date }}.apk
          mv build/ios/iphoneos/app.ipa build/ios/iphoneos/app-${{ env.date }}.ipa
      - name: Upload IPA to Google Drive
        id: upload_ipa
        uses: willo32/google-drive-upload-action@v1
        with:
          target: build/ios/iphoneos/app-${{ env.date }}.ipa
          credentials: ${{ secrets.GDRIVE_KEY }}
          parent_folder_id: ${{ secrets.GDRIVE_FOLDER_ID }}
      - name: Upload APK to Google Drive
        id: upload_apk
        uses: willo32/google-drive-upload-action@v1
        with:
          target: build/app/outputs/apk/release/app-x86_64-release-${{ env.date }}.apk
          credentials: ${{ secrets.GDRIVE_KEY }}
          parent_folder_id: ${{ secrets.GDRIVE_FOLDER_ID }}
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-x86_64-release-${{ env.date }}.apk,build/ios/iphoneos/app-${{ env.date }}.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
      - name: Send notification to Slack
        run: |
          IPA_LINK="https://drive.google.com/file/d/${{ steps.upload_ipa.outputs.file_id }}/view"
          APK_LINK="https://drive.google.com/file/d/${{ steps.upload_apk.outputs.file_id }}/view"
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "New Flutter release build is available. Version: v1.0.${{ github.run_number }}. Download the files here: [IPA](${IPA_LINK}) and [APK](${APK_LINK})"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
