on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' # Use a supported version
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter build apk --release --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Generate Date String
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
      - name: Rename APK and IPA Files
        run: |
          mv build/app/outputs/apk/release/app-x86_64-release.apk build/app/outputs/apk/release/app-x86_64-release-${{ env.date }}.apk
          mv build/ios/iphoneos/app.ipa build/ios/iphoneos/app-${{ env.date }}.ipa
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-x86_64-release-${{ env.date }}.apk,build/ios/iphoneos/app-${{ env.date }}.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
      - name: Send notification to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "New Flutter release build is available. Version: v1.0.${{ github.run_number }}. Files: app-x86_64-release-${{ env.date }}.apk and app-${{ env.date }}.ipa"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
